530 get cdc searchapi visitors information
cessda/cessda.cdc.searchkit pull request #21
Opened 2023-03-16 16:56 UTC by kpapag

2023-03-16 17:08 UTC, john-shepherdson approved these changes

2023-03-17 15:08 UTC, matthew-morris-cessda requested changes

2023-03-17 15:08 UTC, matthew-morris-cessda commented on package.json
> +    "node-ipinfo": "^3.4.0",
Could this be replaced by a fixed version, i.e. `"node-ipinfo": "3.4.0",`?

2023-03-17 15:08 UTC, matthew-morris-cessda commented on package-lock.json
The `package-lock.json` has been reverted to the `v1` format, which is caused by old versions of NPM.

Could you update your version of Node.js and NPM, then run `npm install` again.

2023-03-17 15:08 UTC, matthew-morris-cessda commented on server/helper.ts
> +    const ip: string = req.headers['x-forwarded-for'] as string || req.socket.remoteAddress as string;
`req.headers['x-forwarded-for'] as string` should be `req.headers['x-forwarded-for'] as string | undefined`

Please don't use type assertions like `as` unless you can verify the type.

2023-03-17 15:08 UTC, matthew-morris-cessda commented on server/helper.ts
> +      console.log(error);
This is redundant

2023-03-21 09:24 UTC, matthew-morris-cessda approved these changes
Looks good

2023-03-21 13:27 UTC, merged